[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "crypto-quant-monitor"
version = "0.0.1"
description = "Quant training pipeline with ADML CV and TBM event labeling"
requires-python = "==3.12.3"
readme = "README.md"

dependencies = [
  "matplotlib",
  "pymongo[srv]",
  "apscheduler",
  "ccxt==4.5.33",
  "pandas==3.0.0",
  "pandas-ta==0.4.71b0",
  "PyYAML==6.0.3",
  "numpy==2.2.6",
  "vectorbt==0.28.2",
  "tsfeatures==0.4.5",
  "dotenv==0.9.9",
  "websockets==16.0",
  "aioredis==2.0.1",
  "python-binance==1.0.30",
  "torch==2.9.1",
  "TA-Lib==0.6.8",
  "discord==2.3.2",
  "pydantic>=2.12.5",
]

[tool.setuptools.packages.find]
include = [
  "aggTrade*",
  "backtest*",
  "crawler*",
  "trader*",
  "feature_selection*",
  "orderbook_snapshot*",
  "train*"
]
