exchange:
  id: 'binance'           # 交易所 ID，從 binance 改為 mexc
  default_type: 'swap' # 市場類型，'spot' (現貨) 或 'swap' (永續合約)
data:
  symbols: ["BTCUSDT", "ETHUSDT", "BNBUSDT"]
  interval: "15m" # Options: "1m", "5m", "15m", "1h", "4h", "1d"
  market: "futures" # Options: "spot", "futures"
  lookback: 100
  features:
    long_feature_cfg_path: "configs/feature_108_long.yaml"
    short_feature_cfg_path: "configs/feature_108_short.yaml"
  redis_url: "redis://localhost:6379"
  # rumtime option
  queue_max: 200000
  health_timeout: 30.0
  backoff_base: 1.0
  backoff_max: 60.0

trader:
  type: "futures" # Options: "spot", "futures"
  useTestnet: true
