device: "cuda:0"

data:
  path: data/precomputed/btcusdt_15m_features/btcusdt_15m_features.csv
  micro:
    enabled: true
    path: data/precomputed/btcusdt_15m_features/btcusdt_1m_trades.csv
    window_len: 15  # 1 min 以 15 min 為單位聚合，併入 15 min feat

cv:
  start_date: "2023-01-05"
  end_date: "2025-10-20"

sequence:
  seq_len: 144

label:
  tbm_csv_path: data/TBM_label/win_rate/BTC-USDT_1h_ewma_up8_dn8_lookback108_label.csv
  keep_sides: short # [short | long | both]
  align_method: pad

post_infer:
  enabled: true
  date_start: "2025-05-01"
  date_end: "2025-10-20"
  collapse_mask_enable: true

train:
  batch_size: 256
  amp: true
  amp_dtype: "bf16"

model:
  name: "TwoStreamHybrid"
  num_classes: 2
