exchange:
  id: mexc
  default_type: swap

range:
  start: "2021-01-01"
  end: null

io:
  outdir: "data/ohlcv"
  fmt: "parquet"
  append: true

fetch:
  limit: 1000
  sleep: 0.8
  max_retries: 5

monitoring:
  - symbol: "BTC/USDT:USDT"
    timeframes: ["1h", "4h"]
